AllCops:
  Exclude:
    - 'bin/*'
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'Gemfile'
    - 'Gemfile.lock'
    - 'Guardfile'
    - 'Rakefile'
  TargetRubyVersion: 2.2 # no 2.3 because of frozen strings comment (it's a little bit annoying right now
Documentation:
  Enabled: false
Metrics/LineLength:
  Max: 100
Rails/ActionFilter:
  Enabled: false
Rails/DynamicFindBy:
  Enabled: false
Rails/HttpPositionalArguments:
  Enabled: false
Style/DotPosition:
  EnforcedStyle: leading
SignalException:
  Enabled: false
Style/StringLiterals:
  EnforcedStyle: single_quotes
Style/TrailingCommaInLiteral:
  EnforcedStyleForMultiline: comma
  Enabled: true
Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma
  Enabled: true
Style/PredicateName:
  Exclude:
    - 'app/serializers/**/*'
