version: '3.2'
services:
  web:
    image: ${DOCKER_REPO}:${TIMESTAMP}
    volumes:
      - /var/nfs/props/staging/assets:/app/public/assets
    hostname: "netguru.props.staging.web"
    labels:
      - "netguru.appname=props"
      - "netguru.stage=staging"
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == worker]
      labels:
        - "traefik.frontend.rule=HostRegexp: ${VIRTUAL_HOST}, {subdomain:[a-z]+}.${VIRTUAL_HOST}"
        - "traefik.port=3000"
        - "traefik.docker.network=swarm"
      resources:
        limits:
          cpus: "0.25"
          memory: 800M
    env_file: /home/deploy/apps/props/shared/secrets.env
    networks:
      - swarm
    command: dumb-init puma -C config/puma.rb

networks:
  swarm:
    external:
      name: swarm
