development: &defaults
  allowed_email_domains:
  app_domain: 'props.dev'
  domain_name: 'gapps-domain-name'
  emails:
    default_from: 'props@example.com'
  newrelic_license_key: 'newrelic_license_key'
  omniauth_provider_key: 'omniauth-key'
  omniauth_provider_secret: 'omniauth-secret'
  rollbar_access_token: 'rollbar_token'
  secret_key_base: 'please-change-me'
  sendgrid_password: 'sendgrid_password'
  sendgrid_user_name: 'sendgrid_user_name'
  skylight_token: 'skylight-token'
  slack:
    default_channel: 'default_channel'
    webhook_url: 'webhook_url'

test:
  <<: *defaults

production:
  allowed_email_domains:
  app_domain: <%= ENV['APP_DOMAIN'] %>
  domain_name: <%= ENV['GAPPS_DOMAIN_NAME'] %>
  emails:
    default_from: <%= ENV['EMAILS_DEFAULT_FROM'] %>
  newrelic_license_key: <%= ENV['NEWRELIC_LICENSE_KEY'] %>
  omniauth_provider_key: <%= ENV['OMNIAUTH_KEY'] %>
  omniauth_provider_secret: <%= ENV['OMNIAUTH_SECRET'] %>
  rollbar_access_token: <%= ENV['ROLLBAR_TOKEN'] %>
  secret_key_base: <%= ENV['SECRET_KEY_BASE'] %>
  sendgrid_password: <%= ENV['SENDGRID_PASSWORD'] %>
  sendgrid_user_name: <%= ENV['SENDGRID_USER_NAME'] %>
  skylight_token: <%= ENV['SKYLIGHT_TOKEN'] %>
  slack:
    default_channel: <%= ENV['SLACK_DEFAULT_CHANNEL'] %>
    webhook_url: <%= ENV['SLACK_WEBHOOK_URL'] %>
