development: &defaults
  allowed_email_domains:
  app_domain: 'props.dev'
  domain_name: 'gapps-domain-name'
  emails:
    default_from: 'props@example.com'
  newrelic_license_key: 'newrelic_license_key'
  omniauth_provider_key: 'omniauth-key'
  omniauth_provider_secret: 'omniauth-secret'
  rollbar_access_token: 'rollbar_token'
  secret_key_base: 'please-change-me'
  sendgrid_password: 'sendgrid_password'
  sendgrid_user_name: 'sendgrid_user_name'
  slack:
    default_channel: 'default_channel'
    webhook_url: 'webhook_url'

test:
  <<: *defaults

production:
  <<: *defaults
