require 'preinitializer'

common: &default_settings
  app_name: props
  license_key: AppConfig.newrelic_license_key
  monitor_mode: true
  developer_mode: true
  log_level: info
  ssl: false
  apdex_t: 0.5
  capture_params: true

  transaction_tracer:
    enabled: true
    transaction_threshold: apdex_f
    record_sql: obfuscated
    stack_trace_threshold: 0.500

  error_collector:
    enabled: true
    capture_source: true
    ignore_errors: ActionController::RoutingError

development:
  <<: *default_settings
  developer_mode: true

test:
  <<: *default_settings

staging:
  <<: *default_settings
  monitor_mode: true
  app_name: props (staging)

production:
  <<: *default_settings
  monitor_mode: true
